export const projects = [
  {
    name: "I'M THAT GIRL",
    src: "/images/home/1.png",
    color: "#fff",
    id: "it's_not_the_diamonds.m4a",
  },
  {
    name: "COZY",
    src: "/images/home/2.png",
    color: "#F576C3",
    id: "this_a_reminder.m4a",
  },
  {
    name: "ALIEN SUPERSTAR",
    src: "/images/home/8.png",
    color: "#67C8FB",
    id: "unique.m4a",
  },
  {
    name: "CUFF IT",
    src: "/images/home/10.png",
    color: "#713735",
    id: "fuck_it_up.m4a",
  },
  {
    name: "ENERGY",
    src: "/images/home/4.png",
    color: "#000",
    id: "that_kodak_energy.m4a",
  },
  {
    name: "BREAK MY SOUL",
    src: "/images/home/18.png",
    color: "#E80000",
    id: "i_just_quit_my_job.m4a",
  },
  {
    name: "CHURCH GIRL",
    src: "/images/home/17.png",
    color: "#F05F04",
    id: "drop_it_like_a_thottie.m4a",
  },
  {
    name: "PLASTIC OFF THE SOFA",
    src: "/images/home/12.png",
    color: "#F9D608",
    id: "baby_come_over.m4a",
  },
  {
    name: "VIRGO'S GROOVE",
    src: "/images/home/9.png",
    color: "#0DD431",
    id: "pursue_me.m4a",
  },
  {
    name: "MOVE",
    src: "/images/home/16.png",
    color: "#0100F4",
    id: "its_the_yoncé_groove.m4a",
  },
  {
    name: "HEATED",
    src: "/images/home/11.png",
    color: "#7F0C9B",
    id: "heated.m4a",
  },
  {
    name: "THIQUE",
    src: "/images/home/14.png",
    color: "#EF16AB",
    id: "thique.m4a",
  },
  {
    name: "ALL UP IN YOUR MIND",
    src: "/images/home/13.png",
    color: "#fff",
    id: "all_up_in_your_mind.m4a",
  },
  {
    name: "AMERICA HAS A PROBLEM",
    src: "/images/home/3.png",
    color: "#F576C3",
    id: "america_has_a_problem.m4a",
  },
  {
    name: "PURE/HONEY",
    src: "/images/home/20.png",
    color: "#67C8FB",
    id: "pure_honey.m4a",
  },
  {
    name: "SUMMER RENAISSANCE",
    src: "/images/home/5.png",
    color: "#713735",
    id: "summer_renaissance.m4a",
  },
  // { name: "SUNSHINE", src: "/images/home/6.png", color: "#000" },
  // { name: "BROKEN", src: "/images/home/7.png", color: "#E80000" },
  // { name: "FREAKY", src: "/images/home/19.png", color: "#F05F04" },
  // { name: "SWEET", src: "/images/home/15.png", color: "#F9D608" },
];
