export const projects = [
  { name: "I'M THAT GIRL", src: "/images/home/1.png", color: "#fff" },
  { name: "COZY", src: "/images/home/2.png", color: "#F576C3" },
  { name: "ALIEN SUPERSTAR", src: "/images/home/8.png", color: "#67C8FB" },
  { name: "CUFF IT", src: "/images/home/10.png", color: "#713735" },
  { name: "ENERGY", src: "/images/home/4.png", color: "#000" },
  { name: "BREAK MY SOUL", src: "/images/home/18.png", color: "#E80000" },
  { name: "CHURCH GIRL", src: "/images/home/17.png", color: "#F05F04" },
  {
    name: "PLASTIC OFF THE SOFA",
    src: "/images/home/12.png",
    color: "#F9D608",
  },
  { name: "VIRGO'S GROOVE", src: "/images/home/9.png", color: "#0DD431" },
  { name: "MOVE", src: "/images/home/16.png", color: "#0100F4" },
  { name: "HEATED", src: "/images/home/11.png", color: "#7F0C9B" },
  { name: "THIQUE", src: "/images/home/14.png", color: "#EF16AB" },
  { name: "ALL UP IN YOUR MIND", src: "/images/home/13.png", color: "#fff" },
  {
    name: "AMERICA HAS A PROBLEM",
    src: "/images/home/3.png",
    color: "#F576C3",
  },
  { name: "PURE/HONEY", src: "/images/home/20.png", color: "#67C8FB" },
  { name: "SUMMER RENAISSANCE", src: "/images/home/5.png", color: "#713735" },
  // { name: "SUNSHINE", src: "/images/home/6.png", color: "#000" },
  // { name: "BROKEN", src: "/images/home/7.png", color: "#E80000" },
  // { name: "FREAKY", src: "/images/home/19.png", color: "#F05F04" },
  // { name: "SWEET", src: "/images/home/15.png", color: "#F9D608" },
];
